const key='rose-cx-v4';let state=JSON.parse(localStorage.getItem(key)||'{"checks":{}}');let cid=0;
function ck(text,prefix,cls=''){const id=prefix+'-'+cid++;return `<label class="check ${cls}"><input type="checkbox" data-id="${id}"><span>${text}</span></label>`}
function fitTag(t){return t==='apply'?'<span class="tag ok">APPLY NOW</span>':t==='stretch'?'<span class="tag warn">STRETCH</span>':'<span class="tag">LATER</span>'}
function render(){cid=0;const r=+role.value;
 timeline.innerHTML=stages.map((s,i)=>`<div class="stage"><div class="num">${String(i+1).padStart(2,'0')}</div><div class="stagebox glass ${i===r?'current':''}"><span class="tag ${i===r?'hot':''}">${i===r?'أنت هنا':s.window}</span><h3>${s.role}</h3><p>${s.mission}</p><div class="stagecols"><div><div class="miniTitle">EVIDENCE GATE</div>${s.gate.map(x=>ck(x,'stage'+i)).join('')}</div><div><div class="miniTitle">NEXT POSITION</div><p><b>${s.next}</b></p><p class="source">لا تنتقلي لأن “المدة كملت”. انتقلي عندما تستطيعين إثبات معظم بوابة المرحلة بأمثلة ونتائج.</p></div></div></div></div>`).join('');
 jobgrid.innerHTML=jobs[r].map((j,i)=>`<article class="card job" data-job="${i}"><div>${fitTag(j.type)} <span class="tag">${j.fit}</span></div><h3>${j.title}</h3><p>${j.proof}</p><div class="readiness"><div class="readinessTrack"><div class="readinessBar"></div></div><b class="readinessPct">0%</b></div><div class="miniTitle">READINESS CHECK</div>${j.skills.map(x=>ck(x,'job'+r+'-'+i,'jobcheck')).join('')}</article>`).join('');
 coursegrid.innerHTML=courses.map((c,i)=>`<article class="card course"><div class="priority">${c.phase}</div><h3>${c.title}</h3><p>${c.why}</p>${ck('درست وطبقت المخرجات عمليًا','course'+i)}<div class="linkrow"><a class="link pink" target="_blank" rel="noopener" href="${c.url}">افتح المصدر/الدورة ↗</a></div></article>`).join('');
 certgrid.innerHTML=certs.map((c,i)=>`<article class="card cert"><div class="priority">${c.tier}</div><h3>${c.name}</h3><span class="tag">${c.when}</span><span class="tag">${c.value}</span><p><b>الأهلية/التوقيت:</b> ${c.req}</p><p><b>لماذا:</b> ${c.why}</p>${ck('أنجزت الشهادة / أصبحت مؤهلة لها','cert'+i)}<div class="linkrow"><a class="link pink" target="_blank" rel="noopener" href="${c.url}">المصدر الرسمي ↗</a></div></article>`).join('');
 skillgrid.innerHTML=skills.map((s,i)=>`<article class="card"><div class="priority">${s[1]}</div><h3>${s[0]}</h3><p>${s[2]}</p>${ck('أستطيع شرحها + استخدامها + إثبات مثال','skill'+i)}</article>`).join('');
 plangrid.innerHTML=plan.map((p,i)=>`<article class="card"><div class="priority">${p.w}</div><h3>${p.title}</h3>${p.tasks.map(x=>ck(x,'plan'+i)).join('')}</article>`).join('');
 marketgrid.innerHTML=market.map(m=>`<article class="card market"><div class="priority">${m.kind}</div><h3>${m.title}</h3><p>${m.body}</p><div class="linkrow"><a class="link ghost" target="_blank" rel="noopener" href="${m.url}">راجع المصدر ↗</a></div></article>`).join('');
 bind();update();}
function bind(){document.querySelectorAll('input[type=checkbox]').forEach(b=>{b.checked=!!state.checks[b.dataset.id];b.onchange=()=>{state.checks[b.dataset.id]=b.checked;save();update()}})}
function save(){state.name=name.value;state.years=years.value;state.role=role.value;state.goal=goal.value;localStorage.setItem(key,JSON.stringify(state))}
function update(){const boxes=[...document.querySelectorAll('input[type=checkbox]')],d=boxes.filter(x=>x.checked).length,p=boxes.length?Math.round(d/boxes.length*100):0,r=+role.value;pct.textContent=p+'%';done.textContent=d;left.textContent=boxes.length-d;lvl.textContent='L'+(r+1);ring.style.setProperty('--p',p);status.textContent=p<20?'ابدئي بالـEvidence لا بالشهادات':p<50?'تبنين جاهزية قابلة للإثبات':p<80?'جاهزية قوية — قدمي وكملي':'جاهزية عالية — ركزي على النتائج والترقية';
 document.querySelectorAll('[data-job]').forEach(card=>{const bs=[...card.querySelectorAll('.jobcheck input')],x=bs.length?Math.round(bs.filter(b=>b.checked).length/bs.length*100):0;card.querySelector('.readinessBar').style.width=x+'%';card.querySelector('.readinessPct').textContent=x+'%'});
 const nm=name.value.trim();hello.textContent=(nm?nm+'، ':'')+'أقوى 3 خطوات لك الآن';const yrs=+years.value||0;summary.textContent=r===0&&yrs>=4?`لديك ${yrs} سنوات في الخدمة/الكول سنتر. الأولوية الآن ليست سنة خبرة إضافية؛ الأولوية إثبات leadership + analytics + ownership ثم التقديم على Team Leader وQA، مع WFM/CX كمسارات Stretch حسب مهاراتك.`:`أنت في ${stages[r].role}. الهدف التالي: ${stages[Math.min(r+1,7)].role}. ابنِ Evidence Gate قبل مطاردة مسمى أعلى.`;
 let candidates=[];if(r===0){candidates=['وثّقي 3 إنجازات بأرقام + مثال Coaching/ownership','ابدئي التقديم على Team Leader وQA الآن إذا تستطيعين إثبات المهارات','اختاري Track واحد لمدة 90 يوم: Leadership أو QA أو WFM أو CX']}else{const unchecked=boxes.filter(x=>!x.checked).slice(0,3).map(x=>x.nextElementSibling.textContent);candidates=unchecked.length?unchecked:['وثّقي نتائجك','راجعي الدور التالي','ابدئي التقديم']};actions.innerHTML=candidates.map((x,i)=>`<div class="action"><small>PRIORITY ${i+1}</small><b>${x}</b></div>`).join('');
 const current=stages[r],next=stages[Math.min(r+1,7)];snapshot.innerHTML=`<article class="card"><div class="priority">CURRENT</div><h3>${current.role}</h3><p>${current.mission}</p></article><article class="card"><div class="priority">NEXT</div><h3>${next.role}</h3><p>${next.mission}</p></article><article class="card"><div class="priority">TARGET NOW</div><h3>${jobs[r].filter(j=>j.type==='apply').length} وظائف Apply Now</h3><p>${jobs[r].filter(j=>j.type==='apply').map(j=>j.title).join(' • ')||'ابني بوابة المرحلة أولًا'}</p></article>`;}
if(state.name)name.value=state.name;if(state.years)years.value=state.years;if(state.role)role.value=state.role;if(state.goal)goal.value=state.goal;[name,years,goal].forEach(x=>x.onchange=()=>{save();update()});role.onchange=()=>{save();render()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active')});reset.onclick=()=>{if(confirm('سيتم حذف تقدم هذا المتصفح فقط. هل أنت متأكد؟')){localStorage.removeItem(key);location.reload()}};render();