const market=[
{kind:'Saudi role evidence',title:'Call Center Supervisor — Saudi Arabia',body:'إعلان حديث طلب 4 سنوات Call Center/Customer Service منها سنتان في supervisory/team leadership، مع KPIs وworkforce scheduling وquality monitoring وExcel/reporting. هذا سبب عدم اعتبار 4 سنوات Agent وحدها كافية تلقائيًا للمشرف.',url:'https://sa.linkedin.com/jobs/view/call-center-supervisor-at-future-connect-4439668730'},
{kind:'Saudi role evidence',title:'Customer Service Center Manager — Jeddah/Makkah',body:'إعلان حديث طلب 5+ سنوات في إدارة مراكز الاتصال/الخدمة، و2+ سنوات supervisory/managerial، ومعرفة COPC وKPIs والجودة والتحسين المستمر.',url:'https://sa.linkedin.com/jobs/view/customer-service-center-manager-at-2p-perfect-presentation-4428586237'},
{kind:'Saudi role evidence',title:'Customer Experience Specialist — Saudi Arabia',body:'المهام شملت NPS/CSAT/CES، VoC، journey mapping، complaint RCA، corrective actions، والعمل مع Operations/IT/Digital وغيرها.',url:'https://sa.linkedin.com/jobs/view/customer-experience-specialist-at-gulf-union-al-ahlia-4375515670'},
{kind:'Saudi role evidence',title:'Customer Experience Manager — Saudi Arabia',body:'إعلان CX Manager ركز على CX roadmap، journey optimization، CSAT/NPS/Effort، analytics، cross-functional plans وproject management.',url:'https://sa.linkedin.com/jobs/view/customer-experience-manager-at-ikea-alsulaiman-3986638574'},
{kind:'Saudi role evidence',title:'Head of Customer Experience — Saudi Arabia',body:'متطلبات Head شملت multi-year CX strategy، governance، VoC closed loop، CSAT/NPS/CES، journey optimization والتحول الرقمي.',url:'https://sa.linkedin.com/jobs/view/head-of-customer-experience-at-reef-group-%D9%85%D8%AC%D9%85%D9%88%D8%B9%D8%A9-%D8%B1%D9%8A%D9%81-4288949933'},
{kind:'Saudi role evidence',title:'Director Customer Experience — Riyadh',body:'Director-level CX transformation ركز على strategy، journeys، service blueprints، data-driven personalization، executive stakeholders، business development وقيادة فرق متعددة التخصصات، مع 10+ سنوات في الإعلان.',url:'https://sa.linkedin.com/jobs/view/director-customer-experience-at-salt-4348960981'},
{kind:'Official standard',title:'COPC Best Practices for CX Operations',body:'COPC يركز رسميًا على Leadership & Planning، People، Processes، Performance ويمنح designation بعد الاختبار النهائي.',url:'https://www.copc.com/class-listing/copc-best-practices-for-cx-operations/'},
{kind:'Official credential',title:'CCXP Eligibility',body:'CXPA يوضح أن المسار القياسي يتطلب بكالوريوس + 3 سنوات full-time CX عبر عدة competencies؛ لذلك لا نعامل خبرة المكالمات وحدها تلقائيًا كخبرة CCXP مؤهلة.',url:'https://cxpaglobal.org/get-certified/get-started'},
{kind:'Official credential',title:'ASQ Green Belt',body:'ASQ يطلب 3 سنوات خبرة عمل full-time مدفوعة في Body of Knowledge، ما يجعلها خيارًا منطقيًا لمن لديه 4 سنوات إذا كانت الخبرة ذات صلة.',url:'https://www.asq.org/cert/six-sigma-green-belt'}
];