const skills=[
['SLA / Service Level','Operations','نسبة الاتصالات/التفاعلات المخدومة ضمن الزمن المستهدف. افهمي أثر volume، staffing، AHT وshrinkage عليه.'],['AHT','Operations','Average Handle Time = talk/hold/after-call work حسب تعريف المؤسسة. لا تخفضيه على حساب FCR أو الجودة.'],['FCR','CX + Ops','First Contact Resolution. ارتفاعه قد يخفض repeat contacts ويقلل effort والتكلفة.'],['CSAT','CX','رضا العميل عن تفاعل/خدمة. حللي sample، channel، agent/process drivers ولا تكتفي بالمتوسط.'],['NPS','CX','مقياس ولاء/توصية على مستوى العلاقة أو نقاط محددة. مهم في CX لكنه ليس KPI تشغيليًا وحيدًا.'],['CES','CX','Customer Effort Score. يكشف الاحتكاك وصعوبة إنجاز المهمة.'],['Abandonment','WFM','من غادر قبل الخدمة. حلليه مع wait time، arrival pattern، staffing وIVR.'],['Occupancy','WFM','وقت العمل على contacts مقابل وقت availability. الارتفاع المفرط قد يضر الاستدامة.'],['Adherence','WFM','مدى التزام الموظف بالجدول المخطط؛ مختلف عن attendance.'],['Shrinkage','WFM','وقت مدفوع لا يمكن استخدامه لمعالجة contacts: تدريب، اجتماعات، غياب وغيرها.'],['Forecast Accuracy','WFM','دقة توقع volume/AHT/workload. بدونها يصبح staffing رد فعل لا تخطيطًا.'],['Quality Management','QA','Scorecard + sampling + calibration + feedback + trend analysis + improvement.'],['Root Cause Analysis','Improvement','استخدمي 5 Whys/Fishbone/Pareto بحسب المشكلة؛ المطلوب سبب قابل للتصرف لا وصف العرض.'],['Voice of Customer','CX','اجمعي feedback من surveys، complaints، calls، digital وغيرها؛ صنفي themes وأغلقي الحلقة بإجراءات.'],['Journey Mapping','CX','اربطِي مراحل الرحلة، touchpoints، needs، pain points، moments that matter، metrics وowners.'],['Service Blueprinting','CX','أضيفي frontstage/backstage/process/systems لفهم ما وراء تجربة العميل.'],['Power BI / Excel','Analytics','Power Query، pivots، data cleaning، measures/DAX، dashboards، storytelling.'],['CRM & Contact Center Tech','Technology','افهمي CRM، IVR، routing، queues، recording، QA، WFM، bots، omnichannel وreporting.'],['Coaching','Leadership','Behavior-based feedback، SMART actions، follow-up، documentation، accountability.'],['Performance Management','Leadership','Target → observe → diagnose → coach → action plan → follow-up → consequence/recognition.'],['Financial Acumen','Management','Cost/contact، productivity، staffing cost، vendor cost، ROI/business case.'],['Executive Storytelling','Management','Problem → evidence → impact → options → recommendation → decision needed.']];
const plan=[
{w:'الأسبوع 1–2',title:'اعملي Baseline مهني',tasks:['اكتبي KPIs التي تتعاملين معها فعليًا وتعريف كل واحد','اجمعي 3 إنجازات بأرقام بدون بيانات سرية','حددي هل لديك Coaching/SME/Acting TL/QA exposure','اعملي Skill Gap مقابل Team Leader وQA وWFM وCX']},
{w:'الأسبوع 2–4',title:'Leadership Evidence',tasks:['اطلبي Buddy/Coaching لموظف أو موظفين','شاركي في Calibration أو quality review','خذي ownership لتصعيد أو مشكلة متكررة','اكتبي RCA + corrective action + result']},
{w:'الشهر 1',title:'Analytics Evidence',tasks:['تعلمي Excel advanced أو Power BI حسب مستواك','ابني Dashboard تجريبي: SLA/AHT/FCR/CSAT/volume','اكتبي 5 insights و3 actions من الـDashboard','ابدئي PL-300 فقط إذا ستطبقينه عمليًا']},
{w:'الشهر 2',title:'اختاري Track أساسي',tasks:['Leadership: ICMI supervisor/coaching','QA: scorecard + calibration + quality course','WFM: forecasting/scheduling/adherence','CX: VoC + journey map + NPS/CSAT/CES']},
{w:'الشهر 2–3',title:'ابدئي التقديم قبل اكتمال كل شيء',tasks:['قدمي على Team Leader وQA roles فورًا إذا لديك evidence','قدمي على WFM/CX كـstretch إذا أكملت portfolio المناسب','لا تنتظري COPC/CCXP/PMP قبل الانتقال الأول','عدلي CV ليكون achievements + leadership evidence']},
{w:'نهاية 90 يوم',title:'قرار واضح',tasks:['إما ترقية/نقل داخلي أو pipeline مقابلات خارجي','Portfolio فيه Dashboard + RCA + Coaching/QA/WFM/CX artifact','شهادة واحدة قوية أو خطة امتحان واضحة','خطة 6 أشهر للانتقال إلى المستوى التالي']}
];