const courses=[
{phase:'ابدئي الآن',title:'ICMI Elevate — Contact Center Supervisor Training Series',why:'أقرب تدريب مهني لفجوة Agent → Leader: operational excellence، engagement، metrics، coaching.',url:'https://www.icmi.com/training/courses/icmi-elevate-the-contact-center-supervisor-training-series'},
{phase:'ابدئي الآن',title:'ICMI — Supporting Operational Excellence',why:'يفهمك توازن service level والجودة والstaffing ودور المشرف اليومي.',url:'https://www.icmi.com/training/courses/supporting-operational-excellence'},
{phase:'ابدئي الآن',title:'ICMI — Unlocking Potential Through Coaching',why:'Coaching سلوكي، feedback، SMART goals، وحالات صعبة؛ مهارة حاسمة للـTeam Leader.',url:'https://www.icmi.com/training/courses/unlocking-potential-through-coaching'},
{phase:'ابدئي الآن',title:'ICMI — Foundations in Contact Center Metrics',why:'تعلم اختيار وقراءة KPIs وربطها بالتحسين والقرار بدل حفظ التعاريف.',url:'https://www.icmi.com/training/courses/foundations-in-contact-center-metrics'},
{phase:'QA Track',title:'ICMI — Optimizing Contact Center Quality',why:'Scorecard design، calibration، scoring، coaching feedback، وربط الجودة بأهداف البزنس.',url:'https://www.icmi.com/training/courses/optimizing-contact-center-quality'},
{phase:'WFM Track',title:'ICMI — Workforce Management Principles',why:'Forecasting، workload، staffing، scheduling — أساس قوي لمسار WFM.',url:'https://www.icmi.com/training/courses/workforce-management-principles'},
{phase:'Analytics',title:'Microsoft Learn — PL-300 Study Guide & Learning',why:'Power Query، data modeling، DAX، visualization، analysis. طبقيه على بيانات Contact Center.',url:'https://learn.microsoft.com/en-us/credentials/certifications/resources/study-guides/pl-300'},
{phase:'CX Track',title:'CXPA — Voice of Customer Guide',why:'مرجع مهني لفهم VoC وتحويل طلبات وشكاوى العملاء إلى insight/action.',url:'https://cxpaglobal.org/VOCTopicGuide'},
{phase:'CX Track',title:'CXPA Recognized Training Providers',why:'إذا ستدفعين على تدريب CX/CCXP، اختاري جهة معترفًا بها من CXPA بدل كورسات عشوائية.',url:'https://cxpaglobal.org/get-certified/recognized-training-providers'},
{phase:'Manager',title:'ICMI — Contact Center Management',why:'Strategy، AI/automation، resource planning، operational excellence لمسؤولي الإدارة.',url:'https://www.icmi.com/training/courses/contact-center-management'},
{phase:'Platform',title:'Genesys Beyond Learning Paths',why:'إذا شركتك تستخدم Genesys: مسارات Agent Supervisor، Business User، Admin وغيرها.',url:'https://beyond.genesys.com/explore/learning-path/home'},
{phase:'Platform',title:'Cisco 300-830 CLCCE',why:'إذا البيئة تستخدم Webex Contact Center: routing، reporting، digital channels، AI.',url:'https://cxtaf.cisco.com/site/us/en/learn/training-certifications/exams/clcce.html'}
];
const certs=[
{tier:'CORE • NOW',name:'ASQ Certified Six Sigma Green Belt (CSSGB)',when:'الآن',value:'عالية لمسار التحسين/القيادة',req:'ASQ يتطلب 3 سنوات خبرة عمل مدفوعة full-time في مجالات Body of Knowledge. بخبرة 4 سنوات قد تكونين مؤهلة إذا خبرتك تغطي المتطلبات.',why:'Data-driven problem solving، DMAIC، process improvement. لا تكتفي بالامتحان: نفذي مشروع تحسين.',url:'https://www.asq.org/cert/six-sigma-green-belt'},
{tier:'CORE • NOW',name:'Microsoft Certified: Power BI Data Analyst Associate (PL-300)',when:'الآن',value:'عالية للتحليل والتقارير',req:'لا توجد خبرة مسبقة إلزامية منشورة؛ الامتحان يقيس prepare/model/visualize/analyze/manage Power BI.',why:'تميّزك في reporting وanalytics؛ الشهادة تتجدد سنويًا عبر Microsoft.',url:'https://learn.microsoft.com/en-us/credentials/certifications/data-analyst-associate/'},
{tier:'CORE • LEADERSHIP',name:'COPC Customer Experience Performance Leader',when:'Team Lead → Manager',value:'عالية جدًا لعمليات Contact Center',req:'تحصلين على designation بعد حضور COPC Best Practices for CX Operations واجتياز الاختبار النهائي.',why:'يغطي Leadership & Planning، People، Processes، Performance. COPC ظاهر في متطلبات وظائف إدارة مراكز الخدمة بالسعودية.',url:'https://www.copc.com/class-listing/copc-best-practices-for-cx-operations/'},
{tier:'CX • EXPERIENCE-BASED',name:'CCXP — Certified Customer Experience Professional',when:'بعد بناء خبرة CX حقيقية',value:'عالية لمسار CX',req:'المسار القياسي: بكالوريوس + 3 سنوات full-time CX تغطي عدة competencies؛ البديل: ثانوية + 5 سنوات CX. سنوات Call Center وحدها لا تُحسب تلقائيًا كخبرة CX عريضة.',why:'مناسبة بعد VoC/Journey/Strategy/Metrics/Culture، وليس قبلها.',url:'https://cxpaglobal.org/get-certified/get-started'},
{tier:'MANAGEMENT',name:'PMP — Project Management Professional',when:'Manager / Transformation',value:'عالية عند قيادة مشاريع',req:'اعتبارًا من اختبار 2026: بكالوريوس + 3 سنوات قيادة مشاريع خلال آخر 10 سنوات (أو مسارات أخرى حسب التعليم) + 35 ساعة تدريب مؤهل/بديل CAPM.',why:'مفيدة عندما تقودين CRM، IVR، automation، omnichannel أو transformation. التشغيل الروتيني لا يساوي خبرة مشروع.',url:'https://www.pmi.org/certifications/project-management-pmp'},
{tier:'IMPROVEMENT • LATER',name:'ASQ Certified Six Sigma Black Belt (CSSBB)',when:'Manager → Head',value:'عالية إذا كنت تقودين تحسينًا مؤسسيًا',req:'3 سنوات خبرة ذات صلة + مشروع مكتمل واحد بإفادة موقعة، أو مشروعان مكتملان بإفادات.',why:'للقيادة العميقة في DMAIC وOperational Excellence، وليس مجرد إضافة اسم للسيرة.',url:'https://www.asq.org/cert/six-sigma-black-belt'},
{tier:'PLATFORM • OPTIONAL',name:'Genesys Certifications',when:'حسب منصة الشركة',value:'عالية فقط إذا تستخدمها الشركة/السوق',req:'Genesys Beyond يقدم مستويات Professional/Developer/Specialist حسب المنتج؛ صلاحية Genesys Cloud CX المنشورة سنتان.',why:'لا تأخذيها لمجرد الاسم؛ خذي منصة الشركة التي تستهدفينها.',url:'https://beyond.genesys.com/explore/certification/home'},
{tier:'PLATFORM • OPTIONAL',name:'Cisco Certified Specialist — Collaboration Cloud Customer Experience',when:'حسب منصة الشركة',value:'عالية لبيئات Webex Contact Center',req:'اختبار 300-830 CLCCE، لا prerequisites منشورة، صلاحية 3 سنوات.',why:'Webex Contact Center، telephony/routing، reporting، digital channels، advanced features وAI.',url:'https://cxtaf.cisco.com/site/us/en/learn/training-certifications/exams/clcce.html'},
{tier:'XM • OPTIONAL',name:'Qualtrics XM Certifications',when:'CX Specialist → Manager',value:'مفيدة إذا تستخدم المؤسسة Qualtrics',req:'Qualtrics يقدم Fundamentals، Platform Essentials، XM for CX Expert، وXMP؛ XMP يوصي بـ3 سنوات full-time XM.',why:'مفيدة لـVoC/XM programs والأدوات، لكنها platform-specific.',url:'https://www.qualtrics.com/training/certification/'},
{tier:'SERVICE MGMT • OPTIONAL',name:'ITIL Foundation',when:'اختياري حسب البيئة',value:'متوسطة لهذا المسار',req:'Foundation نقطة البداية الرسمية في ITIL.',why:'مفيد إذا عملك متداخل مع IT service management/support؛ ليس أولوية فوق leadership/analytics/CX.',url:'https://www.peoplecert.org/ITIL-4'},
{tier:'TRANSFORMATION • LATER',name:'Prosci Change Management Certification',when:'Head / Director / Transformation',value:'عالية في التحولات الكبيرة',req:'برنامج تطبيقي مكثف من Prosci؛ راجعي التكلفة والجدول قبل التسجيل.',why:'مفيد لقيادة adoption والتغيير عند تطبيق أنظمة وعمليات وثقافة جديدة.',url:'https://www.prosci.com/solutions/training-programs/change-management-certification-program'},
{tier:'EXPERT • NICHE',name:'ASQ Master Black Belt',when:'فقط لمسار Operational Excellence العميق',value:'ليست مطلوبة لمعظم قادة CX',req:'موجهة لمن يعملون كـMBB أو Black Belts ذوي خبرة كبيرة، مع portfolio review ومتطلبات خبرة.',why:'لا تضعيها ضمن الخطة الافتراضية إلا إذا أصبح التحسين المؤسسي تخصصك الأساسي.',url:'https://www.asq.org/cert/master-black-belt'}
];